// Textos en español fuera del contenido editorial Markdown.
// Las rutas y la configuración permanecen en data.ts y site.ts.
export const TEXTS_GENERAL = {
    locale: { html: 'es', date: 'es-MX', sort: 'es', rss: 'es-mx' },
    site: {
        name: 'CyberEvents.MX',
        description: 'Eventos y archivo histórico de eventos de ciberseguridad en México',
    },
    pages: {
        Home: {
            name: 'Inicio',
            description: 'Fechas, sedes y recursos de eventos de ciberseguridad en México',
        },
        Events: {
            name: 'Eventos',
            description: 'Consulta los eventos actuales y el archivo de eventos pasados de ciberseguridad en México',
        },
        About: {
            name: 'Acerca de',
            description: 'Conoce CyberEvents.MX, el directorio independiente de ciberseguridad en México',
        },
        Archive: {
            name: 'Archivo de eventos',
            description: 'Explora los eventos pasados de ciberseguridad en México por año',
        },
    },
    externalResources: {
        developer: 'Desarrollado por Marcvs Pt',
        cyberThreat: 'Conoce CyberThreat AI (CTAI)',
    },
    validation: {
        dateFormat: 'Usa YYYY-MM-DD',
        calendarDate: 'La fecha debe existir en el calendario',
        webUrl: 'Usa una URL HTTP o HTTPS',
        cfpDates: 'El cierre del CFP no puede preceder a su apertura',
        hashtag: 'Escribe el hashtag sin # ni espacios',
        verification: 'Un evento verificado necesita fecha de revisión y fuentes',
        image: 'Usa una ruta pública local',
        eventDates: 'endDate requiere startDate y no puede ser anterior',
    },
    errors: {
        canonicalSite: 'Define site en astro.config.mjs para generar las URL canónicas.',
        rssSite: 'Define site en astro.config.mjs para generar el RSS.',
        robotsSite: 'Define site en astro.config.mjs para generar robots.txt.',
        sitemapSite: 'Define site en astro.config.mjs para generar el sitemap de eventos.',
    },
    navigation: {
        label: 'Navegación principal',
        home: 'Inicio',
        events: 'Eventos',
        archive: 'Archivo',
        about: 'Acerca de',
        skip: 'Saltar al contenido',
    },
    home: {
        title: 'Tu próxima conexión',
        titleAccent: 'empieza aquí.',
        description: 'Encuentra conferencias, CTF y talleres. Conecta con la comunidad de ciberseguridad en México y conserva lo que cada encuentro deja.',
        primaryAction: 'Explorar los eventos',
        secondaryAction: 'Conocer el proyecto',
        stats: { events: 'Eventos en el directorio', upcoming: 'Próximos y en curso', archive: 'Ediciones en el archivo' },
        sectionTitle: 'Próximos encuentros',
        sectionDescription: 'Fechas para aprender, compartir y encontrarnos.',
        allEvents: 'Ver todos los eventos',
        empty: 'Todavía no hay fechas anunciadas. Explora los eventos para conocer las próximas ediciones.',
    },
    catalog: {
        title: 'Eventos de la comunidad.',
        description: 'Los encuentros que ya están cerca y los que vienen después.',
        empty: 'No hay eventos por ahora. Consulta las ediciones pasadas en el archivo.',
        count: 'eventos',
        archiveAction: 'Explorar el archivo por año',
        navigation: 'Secciones de los eventos',
        groups: {
            near: { title: 'En curso y muy pronto', description: 'Encuentros en marcha o que empiezan en los próximos 30 días.' },
            upcoming: { title: 'Próximos', description: 'Más fechas para tener en el radar, después de los próximos 30 días.' },
            comingSoon: { title: 'Fechas por anunciar', description: 'Ediciones que preparan su siguiente encuentro.' },
            recent: { title: 'Descubre cómo fue', description: 'Encuentros de los últimos dos meses: vuelve a sus recursos y a la conversación.' },
            cancelled: { title: 'Cancelados', description: 'Eventos cuya cancelación ha sido anunciada.' },
        },
    },
    archive: {
        title: 'La historia de nuestros encuentros.',
        description: 'Explora las ediciones pasadas por año y vuelve a sus charlas, fotografías y recursos disponibles.',
        empty: 'Todavía no hay eventos pasados en el archivo.',
        count: 'eventos en el archivo',
        yearCount: 'eventos',
        navigation: 'Años del archivo',
        back: 'Ver los eventos actuales',
    },
    about: {
        title: 'Un lugar para toda',
        titleAccent: 'la comunidad.',
        description: 'CyberEvents.MX reúne la actividad de ciberseguridad en México: antes, durante y después de cada evento.',
        sections: [
            { title: 'Encuentra tu siguiente evento', description: 'Conferencias, congresos, CTF y talleres. Consulta fechas, sedes y enlaces del organizador en una misma página.' },
            { title: 'Conserva lo que se comparte', description: 'Los encuentros terminan, el conocimiento permanece. El archivo reúne ediciones pasadas y enlaza fotografías, charlas y materiales cuando están disponibles.' },
            { title: 'Información con fuentes', description: 'La información se revisa con fuentes oficiales. Los detalles pendientes se identifican y la información dudosa se conserva como borrador hasta verificarla.' },
        ],
        note: 'Somos un directorio independiente. Para confirmar disponibilidad, requisitos y cambios de último momento, consulta siempre los canales del organizador.',
        action: 'Encontrar un evento',
    },
    event: {
        dateLabel: 'Fecha',
        locationLabel: 'Sede',
        formatLabel: 'Modalidad',
        topicsTitle: 'Temas del encuentro',
        dateUnknown: 'Fecha por anunciar',
        locationUnknown: 'Lugar por anunciar',
        breadcrumbLabel: 'Ruta de navegación',
        view: 'Explorar evento',
        official: 'Sitio oficial',
        tickets: 'Entradas y registro',
        linksLabel: 'Enlaces del evento',
        organizer: 'Organiza',
        free: 'Entrada gratuita',
        paid: 'Entrada de pago',
        priceUnknown: 'Precio por confirmar',
        registrationOpen: 'Registro abierto',
        cfpOpen: 'CFP abierto',
        cfp: 'Convocatoria',
        cfpLabels: { open: 'Abierta', closed: 'Cerrada', announced: 'Por anunciar' },
        formats: { 'in-person': 'Presencial', online: 'En línea', hybrid: 'Híbrido' },
        statusLabels: { 'coming-soon': 'Próximamente', upcoming: 'Próximo', ongoing: 'En curso', finished: 'Finalizado', cancelled: 'Cancelado' },
        categories: { conference: 'Conferencia', congress: 'Congreso', meetup: 'Meetup', ctf: 'CTF', bsides: 'BSides', workshop: 'Taller', summit: 'Summit', forum: 'Foro', academic: 'Académico', community: 'Comunidad' },
        resourcesTitle: 'Lo que dejó el encuentro',
        resourceLabels: { photos: 'Fotografías', videos: 'Videos y charlas', slides: 'Presentaciones', aftermovie: 'Aftermovie' },
        conversationTitle: 'Busca el evento en redes',
        conversationDescription: 'Descubre fotos, experiencias y publicaciones de la comunidad.',
        socialLabel: 'Redes del organizador',
        networks: { x: 'X', instagram: 'Instagram', linkedin: 'LinkedIn', youtube: 'YouTube' },
        verificationLabels: { verified: 'Información verificada', 'needs-verification': 'Información pendiente de verificación', unconfirmed: 'Información sin confirmar' },
        checked: 'Revisada el',
        updated: 'Actualizada el',
    },
    footer: {
        description: 'Encuentra conferencias, CTF y talleres de ciberseguridad en México. Conecta con la comunidad y explora los recursos de cada encuentro en nuestro archivo histórico.',
        externalLinks: 'Recursos Externos',
        independent: 'Un directorio independiente, hecho para conectar.',
    },
    notFound: {
        title: 'Página no encontrada',
        description: 'Esta página no está disponible. Puedes explorar los eventos publicados en la sección de Eventos.',
        action: 'Explorar los eventos',
    },
};
